import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.className} antialiased`}>
        <SidebarProvider>
            <div className="flex min-h-screen min-w-screen">
                <AppSidebar />
                <main className="flex-1 p-4 flex items-center justify-center">
                    {children}
                </main>
            </div>
        </SidebarProvider>
        </body>
        </html>
    );
}